--- #YAML:1.0
name:               Imager-Graph
version:            0.08
abstract:           Draws good looking pie graphs
author:
    - Tony Cook <tony@develop-help.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Imager:      0.75
    Test::More:  0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
