--- #YAML:1.0
name:               Imager-Graph
version:            0.10
abstract:           Draws good looking pie graphs
author:
    - Tony Cook <tony@develop-help.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Imager:      0.75
    perl:        5.006
    Test::More:  0.47
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Imager-Graph
    homepage:    http://imager.perl.org/
    repository:  git://git.imager.perl.org/imager-graph.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
