---
abstract: 'Draws good looking charts'
author:
  - 'Tony Cook <tony@develop-help.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Imager-Graph
no_index:
  directory:
    - t
    - inc
requires:
  Imager: 0.75
  Test::More: 0.47
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Imager-Graph
  homepage: http://imager.perl.org/
  repository: git://git.imager.perl.org/imager-graph.git
version: 0.11
